### ISSUE TITLE
Custom Nullability of Types

### ISSUE THREAD

**Issue by BloodWorkXGaming** [blue-veery-gmbh/spring-rest-2-ts#24]
Hello again,

As I am working on a kotlin Project I am trying to implement the nullability check in a way it uses the nullable type hints for that.
While doing that I ran into a couple of Problems: 
1. setAsNullableType seems to be never called (in ModelClassesToTsInterfacesConverter.java) as tested with breakpoints
2. The nullable annotation doesn't seem to be used at all (maybe because of Kotlin interop, but doubt that)
3. In the resulting ts there is a | null on some types, however I don't really understand where and how (maybe due to kotlin auto boxing?)

I tried to extend the `ModelClassesToTsInterfacesConverter` to check for kotlin nullable, however it never seems to be called either even tho I set it with `tsGenerator.setModelClassesConverter(KConverter(jacksonObjectMapper))`

```
    class KConverter(
        objectMapper: com.blueveery.springrest2ts.converters.ObjectMapper?
    ) : ModelClassesToTsInterfacesConverter(objectMapper) {
        override fun setAsNullableType(
            property: Property,
            tsField: TSField,
            nullableTypesStrategy: NullableTypesStrategy
        ) {
            println("---")
            println(property)
            val kp = property.field.kotlinProperty ?: return
            println(kp)
            tsField.isNullable = kp.returnType.isMarkedNullable
        }
    }
```

Thank you very much for any help :)

**Comment by tomasz-wozniak75** [comment]
Hey
Here is a problem because I don't know Kotlin but my colleges are using generator with Kotlin and in fact they had to create own nullable  strategy.

There are following conditions under which nullable  strategy is called:
1. `com/blueveery/springrest2ts/converters/ModelClassesToTsInterfacesConverter.java:74` Interface has properties to iterate in the loop
2. `com/blueveery/springrest2ts/converters/ModelClassesToTsInterfacesConverter.java:76` property is mapped to single TS field (Jackson unwrap could map one java field to many ts fields)
3. `com/blueveery/springrest2ts/converters/ModelClassesAbstractConverter.java:44` getter type is defined for TS field
if these conditions are met nullable strategy is called. 

I think that converter is not required for such problem, it is enough to set your nullable strategy in the generator:
`KotlinNullableTypesStrategy nullableTypesStrategy = new KotlinNullableTypesStrategy();
  tsGenerator.setNullableTypesStrategy(nullableTypesStrategy);` 

Let me know if my hints solved your problem if not I will contact my colleges to learn if some special setup is required for Kotlin

**Comment by BloodWorkXGaming** [comment]
In the meantime I noticed another wierd interaction:

I can seem to get custom Annotations working with the `HasAnnotationJavaTypeFilter`. It just always says false doesn't matter whether it has the annotation or not. Wit the debugger inside the `accept` even says that `annotation` and my custom class are different?

If I however use a different annotation, doesn't matter what, like e.g. `@JsonInclude` it suddenly works. Any idea why that could happen?

**Comment by tomasz-wozniak75** [comment]
Hey
Annotation in the `HasAnnotationJavaTypeFilter` has to have runtime retention, I added proper validation https://github.com/blue-veery-gmbh/spring-rest-2-ts/commit/800ccd58b3b4ff5248e26a042fe61e7e5ba708e1

**Comment by tomasz-wozniak75** [comment]
In version-1.4.0 `TSField` has reference to Property from which it was created, ticket #25 has also been fixed so I will close this ticket
